title: Noah Wiley
logo: /assets/img/profile.jpeg
description: Noah Wiley
theme: jekyll-theme-minimal
# show_downloads: false
# google_analytics: false
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme